module.exports = {
    SEDI_READ: 'SEDI_READ',
    SEDI_WRITE: 'SEDI_WRITE',
    OPERATORI_READ: 'OPERATORI_READ',
    OPERATORI_WRITE: 'OPERATORI_WRITE',
    PERSONE_WRITE: 'PERSONE_WRITE',
    PERSONE_INTERNE_READ: 'PERSONE_INTERNE_READ',
    PERSONE_INTERNE_WRITE: 'PERSONE_INTERNE_WRITE',
    AUTORIZZAZIONI_READ: 'AUTORIZZAZIONI_READ',
    AUTORIZZAZIONI_WRITE: 'AUTORIZZAZIONI_WRITE',
    DIVISIONI_READ: 'DIVISIONI_READ',
    INGRESSI_READ: 'INGRESSI_READ',
    INGRESSI_WRITE: 'INGRESSI_WRITE',
    BADGE_READ: 'BADGE_READ',
    CATEGORIE_READ: 'CATEGORIE_READ',
    AZIENDE_READ: 'AZIENDE_READ'
};