module.exports = {
    SEDI_READ: 'SEDI_READ',
    SEDI_WRITE: 'SEDI_WRITE',
    OPERATORI_READ: 'OPERATORI_READ',
    OPERATORI_WRITE: 'OPERATORI_WRITE',
    PERSONE_INTERNE_READ: 'PERSONE_INTERNE_READ',
    PERSONE_INTERNE_WRITE: 'PERSONE_INTERNE_WRITE',
    PERSONE_AUTORIZZATE_INTERNE_READ: 'PERSONE_AUTORIZZATE_INTERNE_READ',
    PERSONE_AUTORIZZATE_INTERNE_WRITE: 'PERSONE_AUTORIZZATE_INTERNE_WRITE',
    DIVISIONI_READ: 'DIVISIONI_READ'
};